environment:
  matrix:
    - nodejs_version: 10.13.0

clone_depth: 3

branches:
    only:
      - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install

before_build:
  - node --version
  - npm --version

build_script:
  - cmd: "npm run build"

test: off

deploy: off

notifications:
  - provider: Slack
    incoming_webhook:
      secure: CmhfxrWwgtwzO/kXoZWXRUB/Jh05AQ7DvOhToqtpm6dN1wBDp9+VnNqxldpv34uPd09vuUk4Nu/NQFkIswuZA5NYfIFJIFWqwnZExQFzTBA=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
    template: Build <{{buildUrl}}|#{{buildNumber}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}} by {{commitAuthor}} {{status}} in {{duration}}
